environment:
  # Nuxt requires node v8 minimum
  nodejs_version: '12'
  # Encrypt sensitive data (https://ci.appveyor.com/tools/encrypt)
  github_access_token:
    secure: 3z4H3FxmywspE5pGW2tgYnCrUqvELGif1qs5TAa1GXgX3KfjKMkvzkbdU+RuEPRV
  github_email:
    secure: 2Mo62WwerizFrQq5EtvCKg==

# Only run on master branch
branches:
  only:
    - master

# Install scripts. (runs after repo cloning)
install:
  # switch nodejs version
  - ps: Install-Product node $env:nodejs_version
  # generate ssh key for private gitlab repositories
  - ssh-keygen -t rsa -b 2048 -C "francisco@posiziona.eu"
  # install modules
  - npm install
  # generate static files
  - npm run generate
  # configure global git credentials store (https://www.appveyor.com/docs/how-to/git-push/)
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
  - git config --global user.email $env:github_email
  # deploy to GitHub pages
  - npm run deploy

# No tests to run
test: off

# Don't actually build.
build: off